#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Image-IPTCInfo
version:      1.9
version_from: IPTCInfo.pm
installdirs:  site
requires:

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.12
